chdir: /var/www/html/Dalal/
# user: rails
# group: rails
environment: production
address: 0.0.0.0
port: 3000
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 600
require: []
wait: 60
servers: 1
daemonize: true