load_company_events:
  every: 3600s
  class: CompanyEvent
  args:
  description: Runs the perform method in CompanyEvent

load_company:
  every: 900s
  class: Company
  args:
  description: Runs the perform method in Company

